// Generated by ts-to-zod
import { z } from "zod";

export const storyPhraseSchema = z.object({
  phrase: z.string(),
  timeStart: z.number(),
  timeEnd: z.number(),
});

export const indicatorSchema = z.object({
  time: z.number(),
  wordCount: z.number(),
  step: z.union([z.literal(0), z.literal(1), z.literal(2), z.literal(3)]),
});

export const storyTextSchema = z.object({
  whole: z.string(),
  phrases: z.array(storyPhraseSchema),
});

export const storyVersionSchema = z.object({
  version: z.string(),
  reader: z.string(),
  text: storyTextSchema,
  wordCount: z.number(),
  time: z.number(),
  audioURI: z.string(),
});

export const storySchema = z.object({
  title: z.string(),
  slug: z.string(),
  level: z.union([
    z.literal("lett"),
    z.literal("ganske-tungt"),
    z.literal("hardt"),
  ]),
  description: z.string(),
  imageURI: z.string(),
  versions: z.array(storyVersionSchema),
  translations: z.object({
    pl: z.string(),
  }),
});

export const storiesSchema = z.array(storySchema);
